### ISSUE TITLE
执行  dva new myApp 时报错

### ISSUE THREAD

**Issue by raisezhang** [dora-js/dora-plugin-webpack#25]
![image](https://cloud.githubusercontent.com/assets/1481983/18663462/2a498f58-7f51-11e6-9326-2175953ab64c.png)

@sorrycc  帮忙看下     早上还可以创建项目，这会不行   多谢

**Comment by sorrycc** [comment]
https://github.com/cnpm/npminstall/blob/master/lib/get.js#L68
应该是 npminstall 的问题，去 npminstall 库提个 issue 问下吧。

**Comment by sorrycc** [comment]
试试手动执行 `cnpm install dora-plugin-webpack@0.6` 或安装其他的库会不会有问题。

**Comment by raisezhang** [comment]
下午尝试了好几次 都是安装 node_modules 过程中出现问题， 一会是  dora  一会是这个 包？   是 npminstall 不稳定么？

**Comment by dead-horse** [comment]
@raisezhang 重新安装一下 cnpm 吧，这个问题应该已经修复了

**Comment by raisezhang** [comment]
@dead-horse

服务没响应?  
![image](https://cloud.githubusercontent.com/assets/1481983/18664507/69cdf3ae-7f55-11e6-8c37-865813bbf173.png)

更新后 cnpm版本为 4.3.2
![image](https://cloud.githubusercontent.com/assets/1481983/18664542/96a848b6-7f55-11e6-8c7a-f3c2badae7e0.png)

**Comment by raisezhang** [comment]
@sorrycc  @dead-horse   删了重试了一次， ok 了 ~     多谢    是下午有升级么？  还是有其他原因？
